// <auto-generated />
using System;
using MaasHesap2022.Dal.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaasHesap2022.Dal.Migrations
{
    [DbContext(typeof(MaasHesapContext))]
    partial class MaasHesapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaasHesap2022.Entity.Bordrolar.AylikBordro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BrutUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DamgaVergisi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DamgaVergisiIstisnaTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GelirVergisi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GelirVergisiIstisnaTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GelirVergisiMatrahi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IssizlikIsci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KesintilerToplami")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KumulatifGelirVergisiMatrahi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetEleGecenUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgkIsci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AylikBordrolar");
                });

            modelBuilder.Entity("MaasHesap2022.Entity.BrutAsgariUcret.BrutAsgariUcret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BrutAsgariUcret");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 1, 31, 21, 20, 4, 945, DateTimeKind.Local).AddTicks(6486),
                            Tutar = 5004m,
                            Yil = "2022"
                        });
                });

            modelBuilder.Entity("MaasHesap2022.Entity.GelirVergisiDilimleri.GelirVergisiDilim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AltDilim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Oran")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UstDilim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GelirVergisiDilimleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltDilim = 0m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "32.000 TL’ye kadar",
                            Oran = 0.15m,
                            UstDilim = 32000m,
                            Yil = "2022"
                        },
                        new
                        {
                            Id = 2,
                            AltDilim = 32000m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "70.000 TL’nin 32.000 TL’si için 4800 TL. Fazlası",
                            Oran = 0.20m,
                            UstDilim = 70000m,
                            Yil = "2022"
                        },
                        new
                        {
                            Id = 3,
                            AltDilim = 70000m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "250.000 TL’nin 70.000 TL’si için 12.400 TL. Fazlası",
                            Oran = 0.27m,
                            UstDilim = 250000m,
                            Yil = "2022"
                        },
                        new
                        {
                            Id = 4,
                            AltDilim = 250000m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "880.000 TL’nin 250.000 TL’si için 61.000 TL. Fazlası",
                            Oran = 0.35m,
                            UstDilim = 880000m,
                            Yil = "2022"
                        },
                        new
                        {
                            Id = 5,
                            AltDilim = 880000m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "880.000 TL’den fazlasının 880.000 TL’si için 281.500 TL. Fazlası",
                            Oran = 0.40m,
                            UstDilim = 250000m,
                            Yil = "2022"
                        });
                });

            modelBuilder.Entity("MaasHesap2022.Entity.SgkMatrah.SgkMatrahTavan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SgkMatrahTavan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 1, 31, 21, 20, 4, 949, DateTimeKind.Local).AddTicks(8397),
                            Tutar = 37350m,
                            Yil = "2022"
                        });
                });

            modelBuilder.Entity("MaasHesap2022.Entity.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CocukSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEvli")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
